package com.methodica.app.domain.usecase.planning

import com.methodica.app.domain.repository.StudySessionRepository

class DeleteAssessmentPlanUseCase(
    private val repository: StudySessionRepository
) {
    suspend operator fun invoke(assessmentId: Long): Result<Unit> = runCatching {
        repository.deletePlannedAutoGeneratedByAssessment(assessmentId)
    }
}
