package com.methodica.app.domain.usecase.planning

import com.methodica.app.domain.model.PlanningResult
import com.methodica.app.domain.model.PlanningStatus
import com.methodica.app.domain.planning.StudyPlanGenerator
import com.methodica.app.domain.repository.AssessmentRepository
import com.methodica.app.domain.repository.AssessmentTopicRepository
import com.methodica.app.domain.repository.PlanningSettingsRepository
import com.methodica.app.domain.repository.StudySessionRepository
import kotlinx.coroutines.flow.first
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneId

class GenerateAssessmentPlanUseCase(
    private val assessmentRepository:     AssessmentRepository,
    private val assessmentTopicRepository: AssessmentTopicRepository,
    private val studySessionRepository:   StudySessionRepository,
    private val settingsRepository:       PlanningSettingsRepository,
    private val generator:                StudyPlanGenerator
) {
    suspend operator fun invoke(assessmentId: Long): Result<PlanningResult> = runCatching {
        val assessment = assessmentRepository.getAssessment(assessmentId)
            ?: error("Evaluación no encontrada.")

        val topics = assessmentTopicRepository.getTopicsForAssessment(assessmentId)
        val settings = settingsRepository.observeSettings().first()

        val today = LocalDate.now()
        val examDate = Instant.ofEpochMilli(assessment.date)
            .atZone(ZoneId.systemDefault())
            .toLocalDate()

        val windowStart = today.atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli()
        val windowEnd   = examDate.atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli()
        val existingSessions = studySessionRepository.getByRange(windowStart, windowEnd)

        val result = generator.generate(
            assessment               = assessment,
            linkedTopics             = topics,
            settings                 = settings,
            existingSessionsInWindow = existingSessions,
            today                    = today
        )

        // Idempotencia: eliminar sesiones PLANNED auto-generadas previas
        studySessionRepository.deletePlannedAutoGeneratedByAssessment(assessmentId)

        // Solo persistir si no es INFEASIBLE
        if (result.status != PlanningStatus.INFEASIBLE) {
            studySessionRepository.insertAll(result.sessions)
        }

        result
    }
}
