package com.methodica.app.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import com.methodica.app.domain.model.StudySession
import com.methodica.app.domain.model.StudySessionStatus
import com.methodica.app.domain.model.StudySessionType

@Entity(
    tableName   = "study_sessions",
    foreignKeys = [
        ForeignKey(
            entity        = SubjectEntity::class,
            parentColumns = ["id"],
            childColumns  = ["subjectId"],
            onDelete      = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity        = AssessmentEntity::class,
            parentColumns = ["id"],
            childColumns  = ["assessmentId"],
            onDelete      = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity        = TopicEntity::class,
            parentColumns = ["id"],
            childColumns  = ["topicId"],
            onDelete      = ForeignKey.SET_NULL
        )
    ],
    indices = [Index("subjectId"), Index("assessmentId"), Index("topicId"), Index("date")]
)
data class StudySessionEntity(
    @PrimaryKey(autoGenerate = true) val id:              Long = 0,
    val subjectId:       Long,
    val assessmentId:    Long,
    val topicId:         Long?,
    val date:            Long,
    val positionInDay:   Int,
    val durationMinutes: Int,
    val type:            String,   // StudySessionType.name
    val status:          String,   // StudySessionStatus.name
    val isAutoGenerated: Boolean
)

fun StudySessionEntity.toDomain(): StudySession =
    StudySession(
        id              = id,
        subjectId       = subjectId,
        assessmentId    = assessmentId,
        topicId         = topicId,
        date            = date,
        positionInDay   = positionInDay,
        durationMinutes = durationMinutes,
        type            = StudySessionType.valueOf(type),
        status          = StudySessionStatus.valueOf(status),
        isAutoGenerated = isAutoGenerated
    )

fun StudySession.toEntity(): StudySessionEntity =
    StudySessionEntity(
        id              = id,
        subjectId       = subjectId,
        assessmentId    = assessmentId,
        topicId         = topicId,
        date            = date,
        positionInDay   = positionInDay,
        durationMinutes = durationMinutes,
        type            = type.name,
        status          = status.name,
        isAutoGenerated = isAutoGenerated
    )
