package com.methodica.app.data.repository

import com.methodica.app.data.local.dao.StudySessionDao
import com.methodica.app.data.local.entity.toDomain
import com.methodica.app.data.local.entity.toEntity
import com.methodica.app.domain.model.StudySession
import com.methodica.app.domain.repository.StudySessionRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

class StudySessionRepositoryImpl(
    private val dao: StudySessionDao
) : StudySessionRepository {

    override fun observeByDate(date: Long): Flow<List<StudySession>> =
        dao.observeByDate(date).map { entities -> entities.map { it.toDomain() } }

    override fun observeByRange(startDate: Long, endDate: Long): Flow<List<StudySession>> =
        dao.observeByRange(startDate, endDate).map { entities -> entities.map { it.toDomain() } }

    override fun observeByAssessment(assessmentId: Long): Flow<List<StudySession>> =
        dao.observeByAssessment(assessmentId).map { entities -> entities.map { it.toDomain() } }

    override suspend fun getByRange(startDate: Long, endDate: Long): List<StudySession> =
        dao.getByRange(startDate, endDate).map { it.toDomain() }

    override suspend fun insertAll(sessions: List<StudySession>) =
        dao.insertAll(sessions.map { it.toEntity() })

    override suspend fun updateSession(session: StudySession) =
        dao.update(session.toEntity())

    override suspend fun deletePlannedAutoGeneratedByAssessment(assessmentId: Long) =
        dao.deletePlannedAutoGeneratedByAssessment(assessmentId)
}
