package com.methodica.app.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.methodica.app.data.local.entity.StudySessionEntity
import kotlinx.coroutines.flow.Flow

@Dao
interface StudySessionDao {

    @Query("SELECT * FROM study_sessions WHERE date = :date ORDER BY positionInDay ASC")
    fun observeByDate(date: Long): Flow<List<StudySessionEntity>>

    @Query("SELECT * FROM study_sessions WHERE date BETWEEN :startDate AND :endDate ORDER BY date ASC, positionInDay ASC")
    fun observeByRange(startDate: Long, endDate: Long): Flow<List<StudySessionEntity>>

    @Query("SELECT * FROM study_sessions WHERE assessmentId = :assessmentId ORDER BY date ASC, positionInDay ASC")
    fun observeByAssessment(assessmentId: Long): Flow<List<StudySessionEntity>>

    @Query("SELECT * FROM study_sessions WHERE date BETWEEN :startDate AND :endDate ORDER BY date ASC, positionInDay ASC")
    suspend fun getByRange(startDate: Long, endDate: Long): List<StudySessionEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(sessions: List<StudySessionEntity>)

    @Update
    suspend fun update(session: StudySessionEntity)

    @Query("DELETE FROM study_sessions WHERE assessmentId = :assessmentId AND status = 'PLANNED' AND isAutoGenerated = 1")
    suspend fun deletePlannedAutoGeneratedByAssessment(assessmentId: Long)
}
