package com.methodica.app.domain.model

data class StudySession(
    val id:              Long = 0,
    val subjectId:       Long,
    val assessmentId:    Long,
    val topicId:         Long?,
    val date:            Long,              // epoch ms, normalizado al inicio del día
    val positionInDay:   Int,
    val durationMinutes: Int = 60,
    val type:            StudySessionType,
    val status:          StudySessionStatus = StudySessionStatus.PLANNED,
    val isAutoGenerated: Boolean = true
)
