package com.methodica.app.domain.usecase.planning

import com.methodica.app.domain.model.Assessment
import com.methodica.app.domain.model.PlanningSettings
import com.methodica.app.domain.model.StudySession
import com.methodica.app.domain.model.Topic
import com.methodica.app.domain.planning.StudyPlanGenerator
import com.methodica.app.domain.repository.AssessmentRepository
import com.methodica.app.domain.repository.AssessmentTopicRepository
import com.methodica.app.domain.repository.PlanningSettingsRepository
import com.methodica.app.domain.repository.StudySessionRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.emptyFlow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class GenerateAssessmentPlanUseCaseTest {

    @Test
    fun `falla si la evaluacion ya no existe y no persiste sesiones`() = runTest {
        val studySessionRepository = FakeStudySessionRepository()
        val useCase = GenerateAssessmentPlanUseCase(
            assessmentRepository = MissingAssessmentRepository(),
            assessmentTopicRepository = EmptyAssessmentTopicRepository(),
            studySessionRepository = studySessionRepository,
            settingsRepository = FixedPlanningSettingsRepository(),
            generator = StudyPlanGenerator()
        )

        val result = useCase(assessmentId = 99L)

        assertTrue(result.isFailure)
        assertEquals("Evaluación no encontrada.", result.exceptionOrNull()?.message)
        assertTrue(studySessionRepository.deletedAssessmentIds.isEmpty())
        assertTrue(studySessionRepository.insertedBatches.isEmpty())
    }
}

private class MissingAssessmentRepository : AssessmentRepository {
    override fun observeAllAssessments(): Flow<List<Assessment>> = flowOf(emptyList())
    override fun observeAssessments(subjectId: Long): Flow<List<Assessment>> = flowOf(emptyList())
    override suspend fun getAssessment(id: Long): Assessment? = null
    override suspend fun saveAssessment(assessment: Assessment): Long = 0L
    override suspend fun deleteAssessment(assessment: Assessment) = Unit
}

private class EmptyAssessmentTopicRepository : AssessmentTopicRepository {
    override fun observeTopicsForAssessment(assessmentId: Long): Flow<List<Topic>> = flowOf(emptyList())
    override suspend fun getTopicsForAssessment(assessmentId: Long): List<Topic> = emptyList()
    override fun observeTopicIdsForAssessment(assessmentId: Long): Flow<List<Long>> = flowOf(emptyList())
    override suspend fun replaceTopicsForAssessment(assessmentId: Long, topicIds: List<Long>) = Unit
}

private class FixedPlanningSettingsRepository : PlanningSettingsRepository {
    override fun observeSettings(): Flow<PlanningSettings> = flowOf(PlanningSettings())
    override suspend fun saveSettings(settings: PlanningSettings) = Unit
}

private class FakeStudySessionRepository : StudySessionRepository {
    val deletedAssessmentIds = mutableListOf<Long>()
    val insertedBatches = mutableListOf<List<StudySession>>()

    override fun observeByDate(date: Long): Flow<List<StudySession>> = emptyFlow()
    override fun observeByRange(startDate: Long, endDate: Long): Flow<List<StudySession>> = emptyFlow()
    override fun observeByAssessment(assessmentId: Long): Flow<List<StudySession>> = emptyFlow()
    override suspend fun getByRange(startDate: Long, endDate: Long): List<StudySession> = emptyList()

    override suspend fun insertAll(sessions: List<StudySession>) {
        insertedBatches.add(sessions)
    }

    override suspend fun updateSession(session: StudySession) = Unit

    override suspend fun deletePlannedAutoGeneratedByAssessment(assessmentId: Long) {
        deletedAssessmentIds.add(assessmentId)
    }
}

