package com.methodica.app.domain.repository

import com.methodica.app.domain.model.StudySession
import kotlinx.coroutines.flow.Flow

interface StudySessionRepository {
    fun observeByDate(date: Long): Flow<List<StudySession>>
    fun observeByRange(startDate: Long, endDate: Long): Flow<List<StudySession>>
    fun observeByAssessment(assessmentId: Long): Flow<List<StudySession>>
    suspend fun getByRange(startDate: Long, endDate: Long): List<StudySession>
    suspend fun insertAll(sessions: List<StudySession>)
    suspend fun updateSession(session: StudySession)
    suspend fun deletePlannedAutoGeneratedByAssessment(assessmentId: Long)
}
