package com.methodica.app.data.local

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

object AppDatabaseMigrations {

    val MIGRATION_2_3 = object : Migration(2, 3) {
        override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `study_sessions` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `subjectId` INTEGER NOT NULL,
                    `assessmentId` INTEGER NOT NULL,
                    `topicId` INTEGER,
                    `date` INTEGER NOT NULL,
                    `positionInDay` INTEGER NOT NULL,
                    `durationMinutes` INTEGER NOT NULL,
                    `type` TEXT NOT NULL,
                    `status` TEXT NOT NULL,
                    `isAutoGenerated` INTEGER NOT NULL,
                    FOREIGN KEY(`subjectId`) REFERENCES `subjects`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
                    FOREIGN KEY(`assessmentId`) REFERENCES `assessments`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
                    FOREIGN KEY(`topicId`) REFERENCES `topics`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_study_sessions_subjectId` ON `study_sessions` (`subjectId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_study_sessions_assessmentId` ON `study_sessions` (`assessmentId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_study_sessions_topicId` ON `study_sessions` (`topicId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_study_sessions_date` ON `study_sessions` (`date`)")

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `assessment_topic_cross_ref` (
                    `assessmentId` INTEGER NOT NULL,
                    `topicId` INTEGER NOT NULL,
                    PRIMARY KEY(`assessmentId`, `topicId`),
                    FOREIGN KEY(`assessmentId`) REFERENCES `assessments`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
                    FOREIGN KEY(`topicId`) REFERENCES `topics`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_assessment_topic_cross_ref_assessmentId` ON `assessment_topic_cross_ref` (`assessmentId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_assessment_topic_cross_ref_topicId` ON `assessment_topic_cross_ref` (`topicId`)")
        }
    }

    val MIGRATION_3_4 = object : Migration(3, 4) {
        override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `materials` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `subjectId` INTEGER NOT NULL,
                    `topicId` INTEGER,
                    `title` TEXT NOT NULL,
                    `uri` TEXT NOT NULL,
                    `type` TEXT NOT NULL,
                    `createdAt` INTEGER NOT NULL,
                    FOREIGN KEY(`subjectId`) REFERENCES `subjects`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
                    FOREIGN KEY(`topicId`) REFERENCES `topics`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_materials_subjectId` ON `materials` (`subjectId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_materials_topicId` ON `materials` (`topicId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_materials_type` ON `materials` (`type`)")
        }
    }

    val MIGRATION_4_5 = object : Migration(4, 5) {
        override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `ai_documents` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `subjectId` INTEGER NOT NULL,
                    `assessmentId` INTEGER,
                    `materialId` INTEGER,
                    `sourceType` TEXT NOT NULL,
                    `sourceLabel` TEXT NOT NULL,
                    `extractedText` TEXT NOT NULL,
                    `createdAt` INTEGER NOT NULL,
                    FOREIGN KEY(`subjectId`) REFERENCES `subjects`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
                    FOREIGN KEY(`assessmentId`) REFERENCES `assessments`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
                    FOREIGN KEY(`materialId`) REFERENCES `materials`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_documents_subjectId` ON `ai_documents` (`subjectId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_documents_assessmentId` ON `ai_documents` (`assessmentId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_documents_materialId` ON `ai_documents` (`materialId`)")

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `ai_analysis` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `assessmentId` INTEGER NOT NULL,
                    `documentId` INTEGER NOT NULL,
                    `summary` TEXT NOT NULL,
                    `confidence` REAL NOT NULL,
                    `requiresConfirmation` INTEGER NOT NULL,
                    `createdAt` INTEGER NOT NULL,
                    FOREIGN KEY(`assessmentId`) REFERENCES `assessments`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
                    FOREIGN KEY(`documentId`) REFERENCES `ai_documents`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_analysis_assessmentId` ON `ai_analysis` (`assessmentId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_analysis_documentId` ON `ai_analysis` (`documentId`)")

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `exam_scope_analysis` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `analysisId` INTEGER NOT NULL,
                    `estimatedScope` TEXT NOT NULL,
                    `justification` TEXT NOT NULL,
                    `confidence` REAL NOT NULL,
                    `requiresUserConfirmation` INTEGER NOT NULL,
                    FOREIGN KEY(`analysisId`) REFERENCES `ai_analysis`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_exam_scope_analysis_analysisId` ON `exam_scope_analysis` (`analysisId`)")

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `topic_complexity_analysis` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `analysisId` INTEGER NOT NULL,
                    `topicName` TEXT NOT NULL,
                    `isIncludedInScope` INTEGER NOT NULL,
                    `complexityLevel` INTEGER NOT NULL,
                    `recommendedHours` INTEGER NOT NULL,
                    `priority` INTEGER NOT NULL,
                    `requiresPractice` INTEGER NOT NULL,
                    `requiresSpacedReview` INTEGER NOT NULL,
                    `rationale` TEXT NOT NULL,
                    FOREIGN KEY(`analysisId`) REFERENCES `ai_analysis`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_topic_complexity_analysis_analysisId` ON `topic_complexity_analysis` (`analysisId`)")
        }
    }

    val MIGRATION_5_6 = object : Migration(5, 6) {
        override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL(
                """
                ALTER TABLE `subjects`
                ADD COLUMN `degreeName` TEXT NOT NULL DEFAULT 'Sin titulacion'
                """.trimIndent()
            )
            db.execSQL(
                """
                ALTER TABLE `subjects`
                ADD COLUMN `courseYear` INTEGER NOT NULL DEFAULT 1
                """.trimIndent()
            )
        }
    }

    val MIGRATION_6_7 = object : Migration(6, 7) {
        override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `degrees` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `name` TEXT NOT NULL,
                    `description` TEXT
                )
                """.trimIndent()
            )
            db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_degrees_name` ON `degrees` (`name`)")

            db.execSQL(
                """
                INSERT OR IGNORE INTO `degrees`(`name`, `description`)
                SELECT DISTINCT `degreeName`, NULL FROM `subjects`
                """.trimIndent()
            )

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `academic_years` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `degreeId` INTEGER NOT NULL,
                    `yearNumber` INTEGER NOT NULL,
                    `name` TEXT NOT NULL,
                    FOREIGN KEY(`degreeId`) REFERENCES `degrees`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_academic_years_degreeId` ON `academic_years` (`degreeId`)")
            db.execSQL(
                "CREATE UNIQUE INDEX IF NOT EXISTS `index_academic_years_degreeId_yearNumber` ON `academic_years` (`degreeId`, `yearNumber`)"
            )

            db.execSQL(
                """
                INSERT OR IGNORE INTO `academic_years`(`degreeId`, `yearNumber`, `name`)
                SELECT d.`id`, s.`courseYear`, 'Curso ' || s.`courseYear`
                FROM `subjects` s
                INNER JOIN `degrees` d ON d.`name` = s.`degreeName`
                GROUP BY d.`id`, s.`courseYear`
                """.trimIndent()
            )

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `subjects_new` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `academicYearId` INTEGER NOT NULL,
                    `name` TEXT NOT NULL,
                    `colorHex` TEXT NOT NULL,
                    `description` TEXT,
                    FOREIGN KEY(`academicYearId`) REFERENCES `academic_years`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_subjects_new_academicYearId` ON `subjects_new` (`academicYearId`)")

            db.execSQL(
                """
                INSERT INTO `subjects_new`(`id`, `academicYearId`, `name`, `colorHex`, `description`)
                SELECT
                    s.`id`,
                    y.`id`,
                    s.`name`,
                    s.`colorHex`,
                    s.`description`
                FROM `subjects` s
                INNER JOIN `degrees` d ON d.`name` = s.`degreeName`
                INNER JOIN `academic_years` y ON y.`degreeId` = d.`id` AND y.`yearNumber` = s.`courseYear`
                """.trimIndent()
            )

            db.execSQL("DROP TABLE `subjects`")
            db.execSQL("ALTER TABLE `subjects_new` RENAME TO `subjects`")
        }
    }

    val MIGRATION_7_8 = object : Migration(7, 8) {
        override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL(
                """
                ALTER TABLE `degrees`
                ADD COLUMN `status` TEXT NOT NULL DEFAULT 'ACTIVE'
                """.trimIndent()
            )
        }
    }

    

    val MIGRATION_8_9 = object : Migration(8, 9) {
        override fun migrate(db: SupportSQLiteDatabase) {
            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `ai_document_chunks` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `externalId` TEXT NOT NULL,
                    `subjectId` INTEGER NOT NULL,
                    `assessmentId` INTEGER,
                    `topicId` INTEGER,
                    `materialId` INTEGER,
                    `documentId` INTEGER,
                    `sequence` INTEGER NOT NULL,
                    `sourceLabel` TEXT NOT NULL,
                    `content` TEXT NOT NULL,
                    `tokenEstimate` INTEGER NOT NULL,
                    `contentHash` TEXT NOT NULL,
                    `updatedAt` INTEGER NOT NULL,
                    FOREIGN KEY(`subjectId`) REFERENCES `subjects`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
                    FOREIGN KEY(`assessmentId`) REFERENCES `assessments`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
                    FOREIGN KEY(`topicId`) REFERENCES `topics`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
                    FOREIGN KEY(`materialId`) REFERENCES `materials`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
                    FOREIGN KEY(`documentId`) REFERENCES `ai_documents`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL
                )
                """.trimIndent()
            )
            db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_ai_document_chunks_externalId` ON `ai_document_chunks` (`externalId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_document_chunks_subjectId` ON `ai_document_chunks` (`subjectId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_document_chunks_assessmentId` ON `ai_document_chunks` (`assessmentId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_document_chunks_topicId` ON `ai_document_chunks` (`topicId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_document_chunks_materialId` ON `ai_document_chunks` (`materialId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_document_chunks_documentId` ON `ai_document_chunks` (`documentId`)")

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `ai_chunk_embeddings` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `chunkId` INTEGER NOT NULL,
                    `modelVersion` TEXT NOT NULL,
                    `vector` TEXT NOT NULL,
                    `dimensions` INTEGER NOT NULL,
                    `updatedAt` INTEGER NOT NULL,
                    FOREIGN KEY(`chunkId`) REFERENCES `ai_document_chunks`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                )
                """.trimIndent()
            )
            db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_ai_chunk_embeddings_chunkId` ON `ai_chunk_embeddings` (`chunkId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_chunk_embeddings_updatedAt` ON `ai_chunk_embeddings` (`updatedAt`)")

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `ai_indexing_runs` (
                    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                    `subjectId` INTEGER NOT NULL,
                    `assessmentId` INTEGER,
                    `materialId` INTEGER,
                    `status` TEXT NOT NULL,
                    `trigger` TEXT NOT NULL,
                    `startedAt` INTEGER NOT NULL,
                    `completedAt` INTEGER,
                    `errorMessage` TEXT
                )
                """.trimIndent()
            )
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_indexing_runs_subjectId` ON `ai_indexing_runs` (`subjectId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_indexing_runs_assessmentId` ON `ai_indexing_runs` (`assessmentId`)")
            db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_indexing_runs_status` ON `ai_indexing_runs` (`status`)")

            db.execSQL(
                """
                CREATE TABLE IF NOT EXISTS `local_ai_model_state` (
                    `modelType` TEXT NOT NULL,
                    `modelId` TEXT NOT NULL,
                    `modelVersion` TEXT NOT NULL,
                    `status` TEXT NOT NULL,
                    `localPath` TEXT NOT NULL,
                    `requiredDiskBytes` INTEGER NOT NULL,
                    `requiredRamMb` INTEGER NOT NULL,
                    `lastError` TEXT,
                    `updatedAt` INTEGER NOT NULL,
                    PRIMARY KEY(`modelType`)
                )
                """.trimIndent()
            )
        }
    }
val ALL = arrayOf(
        MIGRATION_2_3,
        MIGRATION_3_4,
        MIGRATION_4_5,
        MIGRATION_5_6,
        MIGRATION_6_7,
        MIGRATION_7_8,
        MIGRATION_8_9
    )
}
